# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [3]:
# Given:
import numpy as np 
def similar(lst):
    return lst[0]==lst[-1]

numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]
print("Given list:",numbers_x)
print("result is",similar(numbers_x))
print("Given list:",numbers_y)
print("result is",similar(numbers_y))
# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True
# numbers_y = [75, 65, 35, 75, 30]
# result is False

Given list: [10, 20, 30, 40, 10]
result is True
Given list: [75, 65, 35, 75, 30]
result is False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [4]:
#code here
import numpy as np
numbers_x=np.array([10, 20, 30, 40, 10])
numbers_y=np.array([75, 65, 35, 75, 30])
# Perform element-wise addition
addition_result=numbers_x+numbers_y
print("Element-wise addition result:",addition_result)
# Perform element-wise product
product_result=numbers_x*numbers_y
print("Element-wise product result:",product_result)


Element-wise addition result: [ 85  85  65 115  40]
Element-wise product result: [ 750 1300 1050 3000  300]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [8]:
#code here
import numpy as np
arr1d=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2d=arr1d.reshape(3,4)
print("Reshaped 2D array:")
print(arr2d)
print()
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
horiconcatenated=np.concatenate((arr1,arr2),axis=1) #Concatenate two arrays horizontally
print("Horizontally concatenated array:")
print(horiconcatenated)
print()
vertconcatenated=np.concatenate((arr1,arr2),axis=0) #Concatenate two arrays vertically
print("Vertically concatenated array:")
print(vertconcatenated)


Reshaped 2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Horizontally concatenated array:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Vertically concatenated array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [6]:
shopping_cart = []
print("Welcome to the Online Store Shopping Cart!")
print("Available Products:")
print("1. Piza")
print("2. Burger")
print("3. Quit")
while True:
    choice = input("Enter the number corresponding to the product you want to add to the cart (1-3): ")
    if choice.lower() == 'q':
        break
    try:
        choice = int(choice)
        if choice < 1 or choice > 3:
            print("Invalid choice. Please enter a number between 1 and 3.")
            continue
    except ValueError:
        print("Invalid input. Please enter a number between 1 and 3 or 'q' to quit.")
        continue
    if choice == 1:
        shopping_cart.append("Piza")
    elif choice == 2:
        shopping_cart.append("Burger")
    print("Product added to cart:", shopping_cart[-1])
    print("Updated Shopping Cart:", shopping_cart)
print("\nYour Shopping Cart:")
for item in shopping_cart:
    print("-", item)
print("Thank you for shopping with us!")


Welcome to the Online Store Shopping Cart!
Available Products:
1. Piza
2. Burger
3. Quit
Enter the number corresponding to the product you want to add to the cart (1-3): 1
Product added to cart: Piza
Updated Shopping Cart: ['Piza']
Enter the number corresponding to the product you want to add to the cart (1-3): 2
Product added to cart: Burger
Updated Shopping Cart: ['Piza', 'Burger']
Enter the number corresponding to the product you want to add to the cart (1-3): 3
Product added to cart: Burger
Updated Shopping Cart: ['Piza', 'Burger']
Enter the number corresponding to the product you want to add to the cart (1-3): q

Your Shopping Cart:
- Piza
- Burger
Thank you for shopping with us!


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [1]:
#code here
def classifyemail(emails):
    imp_keyword=["urgent","important","priority"]
    promo_keyword=["sale","offer","discount"]
    spam_keyword=["viagra","lottery","inheritance"]
    imp_email=[]
    promo_email=[]
    spam_email=[]
    for email in emails:
        email_lower=email.lower()
        if any(keyword in email_lower for keyword in imp_keyword):
            imp_email.append(email)
        elif any(keyword in email_lower for keyword in promo_keyword):
            promo_email.append(email)
        elif any(keyword in email_lower for keyword in spam_keyword):
            spam_email.append(email)
    return imp_email,promo_email,spam_email
# Example usage:
emails=[
    "Important: Your account security",
    "Limited time offer",
    "Congratulations, you won a lottery and an iphone!",
    "Urgent: Action required",
    "Exclusive discount for you on satrangi"
]
imp_email,promo_email,spam_email= classifyemail(emails)
print("Important emails:")
print(imp_email)
print()
print("Promotions emails:")
print(promo_email)
print()
print("Spam emails:")
print(spam_email)


Important emails:
['Important: Your account security', 'Urgent: Action required']

Promotions emails:
['Limited time offer', 'Exclusive discount for you on satrangi']

Spam emails:
['Congratulations, you won a lottery and an iphone!']


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [2]:
engspadict={
    "hello": "graisas",
    "goodbye": "basiaso",
    "thank you": "thankiaso",
    "yes": "yesio ",
    "no": "nohn",
}
while True:
    word = input("Enter an English word (or 'exit' to quit): ").lower()
    if word == 'exit':
        print("khatam....jao'_'")
        break
    if word in engspadict:
        print(f"The Spanish translation of '{word}' is '{engspadict[word]}'")
    else:
        print(f"Nahi hai yeah '{word}' mere dictionary main")


Enter an English word (or 'exit' to quit): for
Nahi hai yeah 'for' mere dictionary main
Enter an English word (or 'exit' to quit): hello
The Spanish translation of 'hello' is 'graisas'
Enter an English word (or 'exit' to quit): exit
khatam....jao'_'


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [4]:
import pandas as pd
df= pd.read_csv('https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv')
data=pd.DataFrame(df)
data

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [5]:
import pandas as pd
total_global_sales=data['Global_Sales'].sum()
print("Total Global Sales:",total_global_sales)
game_highest_sales=data.loc[data['Global_Sales'].idxmax()]
print("Game with the highest global sales:")
print(game_highest_sales)
average_sales=data[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']].mean()
print("Average Sales for Each Region:")
print(average_sales)
top_genres=data.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("Top 5 Most Popular Game Genres Based on Global Sales:")
print(top_genres)
sales_by_genre_region=data.groupby('Genre')[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']].sum()
print("Total Sales for Each Genre in Each Region:")
print(sales_by_genre_region)
most_popular_genre_na=sales_by_genre_region['NA_Sales'].idxmax()
print("Most Popular Genre in North America:",most_popular_genre_na)
print("Last 10 rows of the dataset:")
print(data.tail(10))
top_platforms=data.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print("Top 3 Gaming Platforms with the Highest Global Sales:")
print(top_platforms)
market_share=data.groupby('Genre')['Global_Sales'].sum()/total_global_sales*100
print("Market Share (Percentage of Global Sales) for Each Genre:")
print(market_share)
correlation_coefficient=data['NA_Sales'].corr(data['EU_Sales'])
print("Correlation Coefficient between NA_Sales and EU_Sales:",correlation_coefficient)


Total Global Sales: 8920.44
Game with the highest global sales:
Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object
Average Sales for Each Region:
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64
Top 5 Most Popular Game Genres Based on Global Sales:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64
Total Sales for Each Genre in Each Region:
              NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07      